### ISSUE TITLE
SheetLoader missing trailing ; breaks pilets (webpack 5.108+)

### ISSUE THREAD

**Issue by szepaniakjupp** [smapiot/piral#849]
# Bug Report

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

- `piral-cli` / `piral-cli-webpack5`: 1.11.1
- `piral-core`: 1.11.1
- webpack: 5.108.2
- Pilet schema: v2
- Build: production (`pilet build`, minified)

## Description

We recently stumbled upon the following issue, but for now, pinning webpack to v5.107.2 fixed it.

It looks like there might be a latent bug in `SheetLoader` (a missing trailing `;`) that stayed harmless until two changes lined up: (1) webpack **5.108** seems to have changed module emission so the prepended CSS snippet no longer gets a separator before the entry module, and (2) production **minification** strips the newline that previously let ASI insert the missing `;`. As a result, it appears to only break **minified builds on webpack 5.108+** — `pilet debug` and older webpack versions seem unaffected, which might be why it went unnoticed until now.

We could be missing something here, so please let us know if this doesn't match what you're seeing on your end!

Thank you in advance for reviewing!

## Steps to Reproduce

1. Pilet, schema v2, `piral-cli-webpack5@1.11.1`, webpack `5.108.2`
2. Run `pilet build`
3. Inspect the emitted bundle: the CSS-injection snippet is glued to the entry IIFE as `appendChild(e)(()=>{...})()`
4. Load the pilet in a shell

## Expected behavior

Pilet loads; `setup` export is found and called.

## Actual behavior

Pilet fails to initialize, depending on whether it emits a CSS asset:

- Pilet **with** CSS → `TypeError: <x>.head.appendChild(...) is not a function` (guard truthy → `appendChild(e)` returns the `<link>` node → node called as a function).
- Pilet **without** CSS → `SheetPlugin` rewrites `window.__NO_CSS__` → `true`, so the guard is `!true` → `&&` short-circuits → entry IIFE never runs → console warning `Setup function is missing` and nothing is registered.

`pilet debug` (unminified) is unaffected.

## Possible Origin/Solution

Terminate the snippet in `SheetLoader.js` so it can never fuse with following code, regardless of minifier/webpack version:

```js
].join(';') + ';';
```

Verified locally: with the trailing `;`, the minified output becomes `appendChild(e);(()=>{...})()` — the entry IIFE runs as its own statement and `setup` is exported correctly.

**Comment by FlorianRappl** [comment]
Well, the bug is actually on Webpack's side - so I would not call this a latent bug (the omission is on purpose). However, I agree that having the semicolon in general does not hurt - and fixes the Webpack issue (which will also be fixed AFAIK - it actually broke many libs). See https://github.com/webpack/webpack/issues/21288

Will be improved in 1.11.2

General remark: With Piral 1.12 Webpack (5) will no longer be the default (it will most likely be esbuild even though that is not yet decided). The last time we actually used Webpack in any of our own production pilets (customers or services) is well over 2 years ago. In many cases esbuild is better, in any case Vite is better.

**Comment by szepaniakjupp** [comment]
Thanks for the incredibly quick response and for the context!

Also great to hear about the bundler direction for 1.12. We will keep an eye on the esbuild / vite move and likely start looking into it on our side too. Thanks again!

**Comment by FlorianRappl** [comment]
Is fixed in the 1.11.2 (currently out in preview - will be merged later today).
