### ISSUE TITLE
Lodash named imports don't work

### ISSUE THREAD

**Issue by Alellujah** [smapiot/piral#489]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

0.14.16
Windows 10
Chrome

## Description

Well... after upgrading to 0.14.15 and trying out with 0.14.16 I'm having some problems regarding lodash named imports. We have some pilets that are local which work without any problem, the ones that we are fetching we're getting errors as `lodash_1.values is not a function`. 

If we start up any of these pilets locally and change the named imports from ex. `import { values } from "lodash"` to `import values from "lodash"` or even  `import values from "lodash/values"` it works all fine. 

Definetly very weird because rolling back to 0.13.0 we get rid of these issues. 

Our lodash version is `^4.17.21` and typescript `4.2.4`. 

I'm not sure if I should open another issue, but our main reason to be upgrading piral versions is that we have a small transition screen in each pilet loading where we get "not_found" and then it actually starts the loading animation, I've found an old [issue](https://github.com/piral-samples/piral-microfrontend-demo/issues/11) and this seemed this was fixed long ago, but we're seeing it in both 0.13.0 and ^0.14.15.

**Comment by FlorianRappl** [comment]
> we have a small transition screen in each pilet loading where we get "not_found" and then it actually starts the loading animation

That rather sounds like a problem in your loading logic. Piral (by default) itself does not render anything unless everything is loaded - you can change that obviously, but then you need to make the logic right to avoid such issues.

> If we start up any of these pilets locally and change the named imports from ex. import { values } from "lodash" to import values from "lodash" or even import values from "lodash/values" it works all fine.

Hm not really sure here without more details / a MWE. My guess is that you (centrally) share `lodash`? Is that right? In that case imports from `lodash/value` would anyway be bundled and not taken from the shared one.

I am a bit confused about 

> ex. import { values } from "lodash" to import values from "lodash"

as these two are not the same. Maybe you mean `import _ from "lodash; const values = _.values`?

**Comment by FlorianRappl** [comment]
So in general the issue here is that `lodash` is unfortunately no valid ESM module. Why? It exports a function (i.e., does a `module.exports = _`, where `_` is a function. This is impossible with ESM as there you have no notion for such an export. There is, however, `export default _`.

Consequently, inside the module system used for shared dependencies we follow ESM rules. As such the `module.exports = _` will be transformed to `export default _`. The problem now is that lodash made some funky stuff and *added* properties on top of that function (which is valid, of course). Previously, you could do `const { values } = require('lodash')` as it was the same as `const _ = require('lodash'); const { values } = _`, but now things moved differently and you would need to do

```js
import _ from 'lodash';
const { values } = _;
```

(or access it via `_.values`)

I see that this is inconvenient, especially since the typing does not show you that. What we'll do is to expand our compatibility mode to actually see if there are *additional* keys on top of a "moved" default export (i.e., if the star export was a function and thus moved to `default`) and to also alias those. So you could still do:

```js
import { values } from 'lodash';
```

Hope that makes sense.

**Comment by Alellujah** [comment]
> That rather sounds like a problem in your loading logic. Piral (by default) itself does not render anything unless everything is loaded - you can change that obviously, but then you need to make the logic right to avoid such issues.

I'll be looking into that, I'm pretty sure it has something to do how we're loading the pilets with the GraphQL query. Whenever I change the Piral Instance to not use async `async: false` we don't have any issues with that `not_found` transition screen. 

 > Hm not really sure here without more details / a MWE. My guess is that you (centrally) share lodash? Is that right? In that case imports from lodash/value would anyway be bundled and not taken from the shared one.

Yes we have a monorepo. 

About the rest, thanks for looking into it, and for all the help!

**Comment by FlorianRappl** [comment]
> Whenever I change the Piral Instance to not use async async: false we don't have any issues with that not_found transition screen.

Ah that is it then. `async` means that the behavior is only to wait for the metadata, but then pilets are loaded while rendering already. In this way, you'll not have loaded / evaluated / integrated pilets at the time of (first) rendering. Therefore, until the pilets are rendered you'd certainly get a 404 and you'd need to deal with that (e.g., by having a fallback / spinner as 404 while pilets are not done yet).

Since the UX here is more complicated our recommendation (and default) is not to use `async` (or any other loading strategy), but going with the default one. However, under certain circumstances you may want to leverage the full freedom of putting your own loading to work and thus rendering useful information a few ms earlier.

> About the rest, thanks for looking into it, and for all the help!

No problem - patch incoming. Preview should be out in 20 min and if all goes well we'll release 0.14.17 today with the patch.
